### ISSUE TITLE
ViewComponent enhancement

### ISSUE THREAD

**Issue by wwdc14** [lkzhao/UIComponent#3]
Hi,
I want rounded corners, but I don’t know the specific height of this Text component. Is there any way to set it?

It is possible to increase a similar **SwiftUI**`.clipShape(Capsule())`modified it? Because rounded corners are often used

this my code
`Text("Round Style").textColor(.white).inset(h: 20, v: 10).background(SimpleViewComponent<UIView>().backgroundColor(.black))`

actual
<img width="169" alt="iShot2021-07-12 01 52 19" src="https://user-images.githubusercontent.com/11381801/125205242-e392bc80-e2b3-11eb-8b85-2a9794c8f984.png">

expect
<img width="191" alt="iShot2021-07-12 01 55 22" src="https://user-images.githubusercontent.com/11381801/125205324-3b312800-e2b4-11eb-8a4d-3c5ffe239a19.png">

**Comment by lkzhao** [comment]
Hi @wwdc14. 

There are multiple ways to apply a corner radius.

For ViewComponent, you can assign properties of the `UIView` representation via the `.with(_ keyPath: _ value:)` modifier. Something like:
```swift
Text("Round Style").textColor(.white).inset(h: 20, v: 10)
  .background(SimpleViewComponent<UIView>().backgroundColor(.black).with(\.layer.cornerRadius, 20))
```

But if you have the following extension on UIView, you can simplify it further to
```swift
extension UIView {
  @objc open var cornerRadius: CGFloat {
    get { layer.cornerRadius }
    set { layer.cornerRadius = newValue }
  }
}
Text("Round Style").textColor(.white).inset(h: 20, v: 10)
  .background(SimpleViewComponent<UIView>().backgroundColor(.black).cornerRadius(20))
```
This is because `ViewComponent` supports `dynamicMemberLookup`, and any `UIView` properties will become a modifier automatically.

Another important concept that I would like to point out is the difference between a normal `Component` and a `ViewComponent`.
A `ViewComponent` represent a view that is going to be display on screen. And a normal `Component` can be anything including views, layouts, insets, etc...
In your example, the `Text` component is a `ViewComponent` representing a `UILabel`. So you can actually do 
```swift
Text("Round Style").textColor(.white).backgroundColor(.black).cornerRadius(20)
```

However, once you applied the modifier `.inset`, you will see that it becomes a normal `Component` and you can no longer apply the `cornerRadius` modifier, or any other view property modifiers. This is because the `inset` modifier is similar to a layout. It is handled not by rendering a view to the screen, but calculated before the view is actually rendered. This is an optimization done by the framework so that we don't need to render a UIView when it is not necessary.

There is a trick though, you can actually turn any `Component` into a `ViewComponent` using one of the following 3 modifiers:
* `.view()`
* `.scrollView()`
* `.tappableView()`

These 3 modifiers will wrap the component and give you back a `ViewComponent`. You can then do something like this:
```swift
Text("Round Style").textColor(.white).inset(h: 20, v: 10).view().backgroundColor(.black).cornerRadius(20)
```
It will result in a UIView hierarchy like this:
```
<UIView backgroundColor=.black cornerRadius=20 frame=(0, 0, 120, 40)>
    <UILabel textColor=.white text="Round Style" frame=(20, 10, 80, 20) />
</UIView>
```

Compare to the previous example:
```swift
Text("Round Style").textColor(.white).inset(h: 20, v: 10)
  .background(SimpleViewComponent<UIView>().backgroundColor(.black).cornerRadius(20))
```
which will result:
```
<UIView backgroundColor=.black cornerRadius=20 frame=(0, 0, 120, 40) />
<UILabel textColor=.white text="Round Style" frame=(20, 10, 80, 20) />
```


### Fix hardcoded cornerRadius
You might already noticed that the above examples are all using hardcoded value for the `cornerRadius`. This is probably not be desirable in your situation because you wanted a capsule style button with dynamic height. You can actually implement a custom modifier that update the view when it is being rendered:
```swift
extension ViewComponent {
  func capsule() -> ViewUpdateComponent<Self> {
    update {
      $0.layer.cornerRadius = min($0.frame.height, $0.frame.width) / 2
    }
  }
}
```
Then you can just do:
```swift
Text("Round Style").textColor(.white).inset(h: 20, v: 10).view().backgroundColor(.black).capsule()
```

**Comment by wwdc14** [comment]
Thank you very much for answering my doubts, this library is awesome.
